// Generated by CoffeeScript 1.9.1
(function() {
  var assert, data, packer;

  assert = require('assert');

  packer = require('../index');

  data = require('./data');

  describe('packer', function() {
    var res;
    res = null;
    it('should pack data efficiently', function(done) {
      return packer.pack(data, function(err, buffer) {
        if (err) {
          return done(err);
        }
        res = buffer;
        assert(buffer.length <= 128);
        return done();
      });
    });
    return it('should unpack data w/o errors', function(done) {
      return packer.unpack(res, function(err, sample) {
        if (err) {
          return done(err);
        }
        assert.deepEqual(data, sample);
        return done();
      });
    });
  });

}).call(this);
