// Generated by CoffeeScript 1.11.1
(function() {
  var lineByLine;

  lineByLine = require('n-readlines');

  exports.countryIpCounterLineByLine = function(countryCode, cb) {
    var counter, line, liner, re, readChunk, str;
    if (!countryCode) {
      return cb();
    }
    counter = 0;
    liner = new lineByLine(__dirname + "/../data/geo.txt", [readChunk = 4096]);
    re = new RegExp(countryCode, "g");
    while (line = liner.next()) {
      str = line.toString('utf8');
      if (str.match(re)) {
        str = str.split('\t');
        counter += +str[1] - +str[0];
      }
    }
    return cb(null, counter);
  };

}).call(this);
