// Generated by CoffeeScript 1.9.1
(function() {
  exports.pack = function(data, cb) {
    return cb(new Error('Not implemented'));
  };

  exports.unpack = function(buffer, cb) {
    return cb(new Error('Not implemented'));
  };

}).call(this);
